### ISSUE TITLE
[Bug?] lazy-js-utils v0.1.24 caused error in vite-ssg build

### ISSUE THREAD

**Issue by Vincent-the-gamer** [Simon-He95/lazy-js-utils#8]
### Describe the bug

# Bug Description

I was building my blog which is forked from antfu's: [My Blog](https://github.com/Vincent-the-gamer/vincent)

When I upgraded lazy-js-utils to v0.1.24, it caused error: 

node_modules/.pnpm/lazy-js-utils@0.1.24/node_modules/lazy-js-utils/dist/index.mjs (2898:9): "spawn" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/lazy-js-utils@0.1.24/node_modules/lazy-js-utils/dist/index.mjs".

So I downgraded it to v0.1.23 and it works.

# Reproduce

1. Clone my blog: [My Blog](https://github.com/Vincent-the-gamer/vincent)
2. pnpm i
3. pnpm i lazy-js-utils@0.1.24 -D (or lazy-js-utils@latest now)
4. pnpm run build

### Reproduction

https://github.com/Vincent-the-gamer/vincent

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 2.59 GB / 32.00 GB
    Shell: 5.9
Binaries:
    Node: 22.11.0
    npm: 10.9.1
    pnpm: 9.14.2
Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1.1
npmPackages:
    @vitejs/plugin-vue: ^5.2.0 => 5.2.0 
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

pnpm

### Logs

node_modules/.pnpm/lazy-js-utils@0.1.24/node_modules/lazy-js-utils/dist/index.mjs (2898:9): "spawn" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/lazy-js-utils@0.1.24/node_modules/lazy-js-utils/dist/index.mjs".

**Comment by Simon-He95** [comment]
lazy-js-utils@0.1.25 has fixed

**Comment by Vincent-the-gamer** [comment]
Wow, you are lightning-fast !

![740af02e5ee0c798956559bf35a8799d_720](https://github.com/user-attachments/assets/ed45959b-384d-4b9c-9b19-8a546aafa947)
